"""Puertos (interfaces) del dominio. Implementados por adaptadores fuera de core."""
from __future__ import annotations

from datetime import datetime
from decimal import Decimal
from typing import Protocol

from core.entidades import (
    CajaSesion, Categoria, Cliente, Devolucion, Impuesto, MedioPago,
    MovimientoInventario, Pago, Producto, Promocion, Usuario, Venta,
)


class RepositorioCategorias(Protocol):
    def guardar(self, categoria: Categoria) -> Categoria: ...
    def por_id(self, id: int) -> Categoria | None: ...
    def listar(self) -> list[Categoria]: ...


class RepositorioImpuestos(Protocol):
    def guardar(self, impuesto: Impuesto) -> Impuesto: ...
    def por_id(self, id: int) -> Impuesto | None: ...
    def listar(self) -> list[Impuesto]: ...


class RepositorioProductos(Protocol):
    def guardar(self, producto: Producto) -> Producto: ...
    def actualizar(self, producto: Producto) -> Producto: ...
    def por_id(self, id: int) -> Producto | None: ...
    def por_codigo(self, codigo_barras: str) -> Producto | None: ...
    def listar(self) -> list[Producto]: ...


class RepositorioInventario(Protocol):
    def registrar(self, movimiento: MovimientoInventario) -> MovimientoInventario: ...
    def stock_de(self, producto_id: int) -> Decimal: ...
    def movimientos_en(self, desde: datetime, hasta: datetime) -> list[MovimientoInventario]: ...


class RepositorioClientes(Protocol):
    def guardar(self, cliente: Cliente) -> Cliente: ...
    def actualizar(self, cliente: Cliente) -> Cliente: ...
    def por_id(self, id: int) -> Cliente | None: ...
    def por_identificacion(self, identificacion: str) -> Cliente | None: ...
    def listar(self) -> list[Cliente]: ...


class RepositorioMediosPago(Protocol):
    def listar(self) -> list[MedioPago]: ...
    def por_id(self, id: int) -> MedioPago | None: ...


class RepositorioUsuarios(Protocol):
    def guardar(self, usuario: Usuario, hash_password: str) -> Usuario: ...
    def por_id(self, id: int) -> Usuario | None: ...
    def por_nombre(self, nombre: str) -> Usuario | None: ...
    def credencial(self, nombre: str) -> tuple[Usuario, str] | None: ...
    def listar(self) -> list[Usuario]: ...


class RepositorioVentas(Protocol):
    def guardar(self, venta: Venta, pagos: list[Pago]) -> Venta: ...
    def por_id(self, id: int) -> Venta | None: ...
    def pagos_de(self, venta_id: int) -> list[Pago]: ...
    def anular(self, venta_id: int) -> None: ...
    def marcar_estado(self, venta_id: int, estado: str) -> None: ...
    def totales_por_medio(self, caja_sesion_id: int) -> dict[int, Decimal]: ...
    def ventas_en(self, desde: datetime, hasta: datetime) -> list[Venta]: ...
    def pagos_en(self, desde: datetime, hasta: datetime) -> list[Pago]: ...
    def ventas_de_sesion(self, caja_sesion_id: int) -> list[Venta]: ...


class RepositorioCajaSesiones(Protocol):
    def abrir(self, sesion: CajaSesion) -> CajaSesion: ...
    def cerrar(self, sesion: CajaSesion) -> CajaSesion: ...
    def por_id(self, id: int) -> CajaSesion | None: ...
    def abierta(self) -> CajaSesion | None: ...
    def listar(self) -> list[CajaSesion]: ...


class RepositorioDevoluciones(Protocol):
    def guardar(self, devolucion: Devolucion) -> Devolucion: ...
    def por_id(self, id: int) -> Devolucion | None: ...
    def de_venta(self, venta_id: int) -> list[Devolucion]: ...
    def devuelto_por_linea(self, venta_id: int) -> dict[int, Decimal]: ...  # venta_linea_id -> cant.
    def devoluciones_en(self, desde: datetime, hasta: datetime) -> list[Devolucion]: ...
    def de_sesion(self, caja_sesion_id: int) -> list[Devolucion]: ...


class RepositorioPromociones(Protocol):
    def guardar(self, promo: Promocion) -> Promocion: ...
    def actualizar(self, promo: Promocion) -> None: ...
    def por_id(self, id: int) -> Promocion | None: ...
    def activa_por_producto(self, producto_id: int) -> Promocion | None: ...
    def listar(self) -> list[Promocion]: ...
