"""Puertos (interfaces) del dominio. Implementados por adaptadores fuera de core."""
from __future__ import annotations

from decimal import Decimal
from typing import Protocol

from core.entidades import (
    CajaSesion, Categoria, Cliente, Impuesto, MedioPago, MovimientoInventario, Pago, Producto, Venta,
)


class RepositorioCategorias(Protocol):
    def guardar(self, categoria: Categoria) -> Categoria: ...


class RepositorioImpuestos(Protocol):
    def guardar(self, impuesto: Impuesto) -> Impuesto: ...
    def por_id(self, id: int) -> Impuesto | None: ...


class RepositorioProductos(Protocol):
    def guardar(self, producto: Producto) -> Producto: ...
    def por_id(self, id: int) -> Producto | None: ...
    def por_codigo(self, codigo_barras: str) -> Producto | None: ...
    def listar(self) -> list[Producto]: ...


class RepositorioInventario(Protocol):
    def registrar(self, movimiento: MovimientoInventario) -> MovimientoInventario: ...
    def stock_de(self, producto_id: int) -> Decimal: ...


class RepositorioClientes(Protocol):
    def guardar(self, cliente: Cliente) -> Cliente: ...
    def por_id(self, id: int) -> Cliente | None: ...
    def por_identificacion(self, identificacion: str) -> Cliente | None: ...
    def listar(self) -> list[Cliente]: ...


class RepositorioMediosPago(Protocol):
    def listar(self) -> list[MedioPago]: ...
    def por_id(self, id: int) -> MedioPago | None: ...


class RepositorioVentas(Protocol):
    def guardar(self, venta: Venta, pagos: list[Pago]) -> Venta: ...
    def por_id(self, id: int) -> Venta | None: ...
    def pagos_de(self, venta_id: int) -> list[Pago]: ...
    def anular(self, venta_id: int) -> None: ...
    def totales_por_medio(self, caja_sesion_id: int) -> dict[int, Decimal]: ...


class RepositorioCajaSesiones(Protocol):
    def abrir(self, sesion: CajaSesion) -> CajaSesion: ...
    def cerrar(self, sesion: CajaSesion) -> CajaSesion: ...
    def por_id(self, id: int) -> CajaSesion | None: ...
    def abierta(self) -> CajaSesion | None: ...
